Лабораторная работа №1
Saint2999/gifyS_dev pull request #1
Opened 2022-10-17 14:08 UTC by Saint2999

2022-10-18 12:16 UTC, dkorkin requested changes

2022-10-18 12:16 UTC, dkorkin commented on Podfile
> +# Uncomment the next line to define a global platform for your project
Нужно добавить в репазиторий .gitignore

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/CustomCollectionViewLayout.swift
> +{
скобки не по нотации гайдлайна, что я кидал

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/CustomCollectionViewLayout.swift
> +    {
и тут)

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/GifCollectionViewCell.swift
> +    let mainImageView: UIImageView =
через lazy давай делать

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/GifCollectionViewCell.swift
> +        super.init(frame: CGRect())
сюда frame передаем

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/GifCollectionViewCell.swift
> +        mainImageView.image = UIImage(systemName: "sparkles")
вынести в хелпер где бы все имена были константами

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/GifCollectionViewCell.swift
> +//        let gif_url = "https://api.giphy.com/v1/gifs/random?&api_key=YAmokY0BTS38W0ynjXpAq1uJYmfjHYdj"
комменты удаляем

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/GifCollectionViewCell.swift
> +//        let gif_url = "https://api.giphy.com/v1/gifs/random?&api_key=YAmokY0BTS38W0ynjXpAq1uJYmfjHYdj"
комменты удаляем

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/GifCollectionViewCell.swift
> +//        let request = AF.request(gif_url)
может KingFisher or SDWebImage?

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomTableViewCells/ButtonTableViewCell.swift
> +{
тут должен быть делагат и протокол чтобы передать нажатие по кнопке в контроллер

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomTableViewCells/TextFieldTableViewCell.swift
> +        if reuseIdentifier == "UsernameTextFieldTableViewCell" || reuseIdentifier == "EmailTextFieldTableViewCell"
так не делается, ты можешь передавать енам значение ячейки .email .password и конфигурировать все элементы на didSet проперти UsernameTextFieldTableViewCell и EmailTextFieldTableViewCell это 1 и та же ячейка не нужны разные идентификаторы

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomTableViewCells/TextFieldTableViewCell.swift
> +            mainTextField.attributedPlaceholder = NSAttributedString(string: "Password", attributes: [NSAttributedString.Key.foregroundColor: UIColor.systemPurple])
вынести в localized strings написать категорию

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomTableViewCells/TextFieldTableViewCell.swift
> +            mainImageView.contentMode = .scaleAspectFit
очень много кода в 1ом методе раздели на разные методы для текстфилда и картинки

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomTableViewCells/TextFieldTableViewCell.swift
> +            mainImageView.addGestureRecognizer(tapGestureRecognizer)
почему делаешь не кнопкой?

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomTableViewCells/TextFieldTableViewCell.swift
> +            mainTextField.isSecureTextEntry = false
у кнопки есть .selected state и там можно картинки под разные состояния ставить, этот код не был бы нужен

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomTableViewCells/TextFieldTableViewCell.swift
> +    override func becomeFirstResponder() -> Bool
а зачем это тебе?

2022-10-18 12:16 UTC, dkorkin commented on gifyS/CustomTableViewCells/TextFieldTableViewCell.swift
> +            self.text?.removeAll()
и это все?))

2022-10-18 12:16 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnInteractor.swift
> +    var validationResultEmail: ValidationResult = .invalid([ErrorCode(message: "Required", errorCode: ErrorCodes.required)])
вынести строки

2022-10-18 12:16 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnViewController.swift
> +    weak var imageCell: ImageTableViewCell?
не выносим ячефки как проперти, для валидации ищем по ключу

2022-10-18 12:16 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnViewController.swift
> +        emailCell?.mainTextField.addTarget(self, action: #selector(self.emailDidChange), for: .editingDidEnd)
нельзя обращаться к внутренним проперти, сделай их приватными, все общение через делегата

2022-10-18 12:16 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnViewController.swift
> +        imageCell = tableView?.cellForRow(at: IndexPath(row: 0, section: 0)) as? ImageTableViewCell
так не пойдет)

2022-10-18 12:16 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnViewController.swift
> +            imageCell?.mainImageView.tintColor = UIColor.systemGreen
тоже нарушаем инкапсуляцию

2022-10-18 12:16 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnViewController.swift
> +            emailCell?.mainTextField.text = ""
и тут))

2022-10-18 12:16 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnViewController.swift
> +extension AuthnViewController
можно написать какой протокол тут реализуем

2022-10-18 12:16 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnViewController.swift
> +        switch indexPath.section
надо сделать этот метод в 3 строки, мы просто передаем по indexpath.row значение енама и берем у фабричного метода нужную ячейку - передавать можно протокол (value, key, isValid, validationMessage)

2022-10-18 12:16 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnWorker.swift
> +    let login_url = "https://mainsoup.backendless.app/api/users/login"
вынести в константы

2022-10-18 12:16 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnWorker.swift
> +    func signIn(login: String?, password: String?, completionHandler: @escaping (Bool) -> Void)
передавать лучше модельный объект login password

2022-10-18 12:16 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnWorker.swift
> +        AF.request(login_url, method: .post, parameters: login, encoder: JSONParameterEncoder.default, headers: headers).response
нужен базовый нетворк менеджер который будет обрабатывать ответы и собирать хедер + тип запроса, а в воркере вызовы этих общих методов

2022-10-18 12:16 UTC, dkorkin commented on gifyS/Scenes/GifColl/GifCollInteractor.swift
> +  //var name: String = ""
убираем?

2022-10-18 12:16 UTC, dkorkin commented on gifyS/Scenes/GifColl/GifCollRouter.swift
> +  // MARK: Routing
ну и тут, посмотри как ройтинг в вайпере работает через аппконтейнер лучше всего

2022-10-18 12:16 UTC, dkorkin commented on gifyS/Scenes/Reg/RegViewController.swift
> +    weak var tableView: UITableView?
аналогичная история

2022-11-07 19:07 UTC, Saint2999 commented on gifyS/CustomTableViewCells/TextFieldTableViewCell.swift
> +    override func becomeFirstResponder() -> Bool
Для того чтобы не удалялся из поля пароль при переключении защищенного режима

2022-11-20 13:05 UTC, dkorkin requested changes

2022-11-20 13:05 UTC, dkorkin commented on gifyS/AppDelegate.swift
> +        //let vc = AuthnViewController(nibName: nil, bundle: nil)
убираем комменты

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/CollectionViewCellFactory.swift
> +    func configureCell(viewController: GifDescViewController?, gif: HelperGifCollDesc.DisplayedGif?, component: HelperGifCollDesc.CollectionComponents, indexPath: IndexPath) -> UICollectionViewCell {
можем модель передавать, не хелпер сюда

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/CollectionViewCellFactory.swift
> +            vc.imageDelegate = ImageCollectionViewCell
делегату ячейки передается контроллер, но не делегат котроллера ячейка неверный архитектурный подход (снизу вверх всегда)

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/CollectionViewCellFactory.swift
> +            if let url = gif?.bannerURL {
это тоже не верно

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/CollectionViewCellFactory.swift
> +    func configureCell(viewController: GifDescViewController?, gif: HelperGifCollDesc.DisplayedGif?, component: HelperGifCollDesc.CollectionComponents, indexPath: IndexPath) -> UICollectionViewCell {
передавай тогда коллекшен вью?

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/CollectionViewCellFactory.swift
> +    func configureCell(viewController: GifDescViewController?, gif: HelperGifCollDesc.DisplayedGif?, component: HelperGifCollDesc.CollectionComponents, indexPath: IndexPath) -> UICollectionViewCell {
почему не сделать class func?

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/CollectionViewCellFactory.swift
> +final class CollectionViewCellFactory {
можно тогда статик

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/CollectionViewCellFactory.swift
> +                for: indexPath
тут будут аналогичные проблемы

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/CustomCollectionViewLayout.swift
> +            let gifHeight = delegate?.getHeight(indexPath: indexPath) ?? 180
тут передавай можели для расчета

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/GifCollectionViewCell.swift
> +        self.contentView.addSubview(mainGifView)
вынеси в метод createUI и там уже работу с вью

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/GifCollectionViewCell.swift
> +        mainGifView.stopAnimating()
занилить урл гифки рекомендую

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/GifCollectionViewCell.swift
> +        gifInfo = gif
это в коде ячейке не перегруженном сеттере моделе

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/ImageCollectionViewCell.swift
> +        self.backgroundColor = Helper.backgroundColor
вынести в отдельный метод работу

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/LabelCollectionViewCell.swift
> +    private var component: HelperGifCollDesc.CollectionComponents = .title {
почему переставляешь констрейны?

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomCollectionViewStuff/LabelCollectionViewCell.swift
> +    func setComponent(component: HelperGifCollDesc.CollectionComponents) {
этого тут не должно быть

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomTableViewCells/LabelTableViewCell.swift
> +                mainLabel.text = "Sign Up"
локализованные строки

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomTableViewCells/LabelTableViewCell.swift
> +        mainLabel.isUserInteractionEnabled = true
1й метод для лейблы, 2ой для рекогнайзера

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomTableViewCells/TableViewCellFactory.swift
> +        switch signType {
выглядит плохо, передача контролера приведение вк типу, а если у тебя ячейка может быть использована в 5 контроллерах?

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomTableViewCells/TableViewCellFactory.swift
> +        switch signType {
ты можешь протокол передавать

2022-11-20 13:05 UTC, dkorkin commented on gifyS/CustomTableViewCells/TextFieldTableViewCell.swift
> +            mainTextField.attributedPlaceholder = NSAttributedString(string: "Email", attributes: [NSAttributedString.Key.foregroundColor: Helper.primaryColor])
локализация

2022-11-20 13:05 UTC, dkorkin commented on gifyS/Helpers/HelperGifCollDesc.swift
> +    struct DisplayedGif {
вынести объектные модели отдельно

2022-11-20 13:05 UTC, dkorkin commented on gifyS/Helpers/HelperGifCollDesc.swift
> +    static let collectionLabelCellIdentifier: String = "LabelCollectionViewCell"
почему тут и строки сети и названия ячееек, может Constants надо сделать? но ячейки все-равно лучше в базовом классе ячеек или протоколе

2022-11-20 13:05 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnViewController.swift
> +        navigationItem.backBarButtonItem = UIBarButtonItem(title: "Back", style: .plain, target: nil, action: nil)
метод setupTableView а работаешь с navigationItem?

2022-11-20 13:05 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnViewController.swift
> +        imageDelegate = tableView.cellForRow(at: IndexPath(row: 0, section: 0)) as? AuthnVCImageDelegate
плохой подход

2022-11-20 13:05 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnViewController.swift
> +        let email = emailDelegate?.getText()
зачем это все хранить? если по сюти делегат может прокинуть текст в методе своем

2022-11-20 13:05 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnViewController.swift
> +        showSuccess(success: viewModel.success)
почему не презентер?

2022-11-20 13:05 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnViewController.swift
> +        if success {
почему не презентер?

2022-11-20 13:05 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnViewController.swift
> +        if let emailError = viewModel.errorMessageEmail {
почему не презентер?

2022-11-20 13:05 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnViewController.swift
> +            emailDelegate?.setText(text: "")
надо искать ячейку из визибле целов по ключу, ключ и проперти может быть протоколом

2022-11-20 13:05 UTC, dkorkin commented on gifyS/Scenes/Authn/AuthnWorker.swift
> +    func validateEmail(email : String) -> ValidationResult {
валидаторы можно вынести

2022-11-20 13:05 UTC, dkorkin commented on gifyS/Scenes/GifColl/GifCollViewController.swift
> +        navigationItem.backBarButtonItem = UIBarButtonItem(title: "Back", style: .plain, target: nil, action: nil)
опять же

2022-11-20 13:05 UTC, dkorkin commented on gifyS/Scenes/GifColl/GifCollViewController.swift
> +        UINavigationBar.appearance().standardAppearance = appearance
setupSearchBar а почему-то  UINavigationBar.appearance может еще 1 метод customiseNavigation()?

2023-01-09 11:09 UTC, merged